-- MySQL Script generated by MySQL Workbench
-- Tue Oct  1 14:49:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema asistencia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema asistencia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asistencia` DEFAULT CHARACTER SET utf8 ;
USE `asistencia` ;

-- -----------------------------------------------------
-- Table `asistencia`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`personas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `remember_token` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_personas_idx` (`persona_id` ASC),
  CONSTRAINT `fk_users_personas`
    FOREIGN KEY (`persona_id`)
    REFERENCES `asistencia`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`semestres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`semestres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`estudiantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `semestre_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudiantes_personas_idx` (`persona_id` ASC),
  INDEX `fk_Estudiantes_semestres_idx` (`semestre_id` ASC),
  CONSTRAINT `fk_estudiantes_personas`
    FOREIGN KEY (`persona_id`)
    REFERENCES `asistencia`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiantes_semestres`
    FOREIGN KEY (`semestre_id`)
    REFERENCES `asistencia`.`semestres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `semestre_id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `aula` VARCHAR(45) NULL,
  `tema` VARCHAR(45) NULL,
  `software` VARCHAR(45) NULL,
  `avance` INT NULL,
  `fecha` DATE NOT NULL,
  `proyector` INT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cursos_semestres_idx` (`semestre_id` ASC),
  CONSTRAINT `fk_cursos_semestres`
    FOREIGN KEY (`semestre_id`)
    REFERENCES `asistencia`.`semestres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`estudiantes-cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`estudiantes-cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estudiante_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_asignados_estudiantes_idx` (`estudiante_id` ASC),
  INDEX `fk_asignados_cursos_idx` (`curso_id` ASC),
  CONSTRAINT `fk_estudiantes-cursos_estudiantes`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `asistencia`.`estudiantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiantes-cursos_cursos`
    FOREIGN KEY (`curso_id`)
    REFERENCES `asistencia`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`docentes-cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`docentes-cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `docentes_id` INT NOT NULL,
  `cursos_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_docentes-cursos_docentes_idx` (`docentes_id` ASC),
  INDEX `fk_docentes-cursos_cursos_idx` (`cursos_id` ASC),
  CONSTRAINT `fk_docentes-cursos_docentes`
    FOREIGN KEY (`docentes_id`)
    REFERENCES `asistencia`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_docentes-cursos_cursos`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `asistencia`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`asignados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`asignados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estudiante_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_asignados_estudiantes_idx` (`estudiante_id` ASC),
  INDEX `fk_asignados_cursos_idx` (`curso_id` ASC),
  CONSTRAINT `fk_asignados_estudiantes`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `asistencia`.`estudiantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignados_cursos`
    FOREIGN KEY (`curso_id`)
    REFERENCES `asistencia`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
