-- MySQL Script generated by MySQL Workbench
-- Fri Oct 11 05:15:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistema_asistencias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_asistencias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_asistencias` DEFAULT CHARACTER SET utf8 ;
USE `sistema_asistencias` ;

-- -----------------------------------------------------
-- Table `sistema_asistencias`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`personas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `rol_id` INT NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `remember_token` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_personas_idx` (`persona_id` ASC),
  INDEX `fk_users_roles_idx` (`rol_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_users_personas`
    FOREIGN KEY (`persona_id`)
    REFERENCES `sistema_asistencias`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`rol_id`)
    REFERENCES `sistema_asistencias`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`semestres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`semestres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` INT NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`estudiantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `semestre_id` INT NOT NULL,
  `codigo` VARCHAR(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudiantes_personas_idx` (`persona_id` ASC),
  INDEX `fk_Estudiantes_semestres_idx` (`semestre_id` ASC),
  CONSTRAINT `fk_estudiantes_personas`
    FOREIGN KEY (`persona_id`)
    REFERENCES `sistema_asistencias`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiantes_semestres`
    FOREIGN KEY (`semestre_id`)
    REFERENCES `sistema_asistencias`.`semestres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`docentes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_docentes_personas_idx` (`persona_id` ASC),
  CONSTRAINT `fk_docentes_personas`
    FOREIGN KEY (`persona_id`)
    REFERENCES `sistema_asistencias`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `docente_id` INT NOT NULL,
  `semestre_id` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `codigo` VARCHAR(4) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cursos_semestres_idx` (`semestre_id` ASC),
  INDEX `fk_cursos_docentes_idx` (`docente_id` ASC),
  CONSTRAINT `fk_cursos_semestres`
    FOREIGN KEY (`semestre_id`)
    REFERENCES `sistema_asistencias`.`semestres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_docentes`
    FOREIGN KEY (`docente_id`)
    REFERENCES `sistema_asistencias`.`docentes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`asistencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`asistencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `curso_id` INT NOT NULL,
  `docente_id` INT NOT NULL,
  `aula` VARCHAR(3) NULL,
  `tema` VARCHAR(50) NULL,
  `software` VARCHAR(20) NULL,
  `avance` INT NULL,
  `fecha` DATE NULL,
  `proyector` INT NULL DEFAULT 0,
  `laboratorio` INT NOT NULL DEFAULT 0,
  `habilitado` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_asistencias_cursos_idx` (`curso_id` ASC),
  INDEX `fk_asistencias_docentes_idx` (`docente_id` ASC),
  CONSTRAINT `fk_asistencias_cursos`
    FOREIGN KEY (`curso_id`)
    REFERENCES `sistema_asistencias`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asistencias_docentes`
    FOREIGN KEY (`docente_id`)
    REFERENCES `sistema_asistencias`.`docentes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`estudiantes_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`estudiantes_cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estudiante_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_asignados_estudiantes_idx` (`estudiante_id` ASC),
  INDEX `fk_estudiantes-cursos_cursos_idx` (`curso_id` ASC),
  CONSTRAINT `fk_estudiantes-cursos_estudiantes`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `sistema_asistencias`.`estudiantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiantes-cursos_cursos`
    FOREIGN KEY (`curso_id`)
    REFERENCES `sistema_asistencias`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`estudiantes_asistencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`estudiantes_asistencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estudiante_id` INT NOT NULL,
  `asistencia_id` INT NOT NULL,
  `firma` INT NOT NULL DEFAULT 0,
  `nota` INT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudiantes_asistencias_estudiantes_idx` (`estudiante_id` ASC),
  INDEX `fk_estudiantes_asistencias_asistencias_idx` (`asistencia_id` ASC),
  CONSTRAINT `fk_estudiantes_asistencias_asistencias`
    FOREIGN KEY (`asistencia_id`)
    REFERENCES `sistema_asistencias`.`asistencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiantes_asistencias_estudiantes`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `sistema_asistencias`.`estudiantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
