-- MySQL Script generated by MySQL Workbench
-- Thu Oct  3 09:43:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistema_asistencias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_asistencias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_asistencias` DEFAULT CHARACTER SET utf8 ;
USE `sistema_asistencias` ;

-- -----------------------------------------------------
-- Table `sistema_asistencias`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`personas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `remember_token` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_personas_idx` (`persona_id` ASC),
  CONSTRAINT `fk_users_personas`
    FOREIGN KEY (`persona_id`)
    REFERENCES `sistema_asistencias`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`semestres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`semestres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`estudiantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `semestre_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudiantes_personas_idx` (`persona_id` ASC),
  INDEX `fk_Estudiantes_semestres_idx` (`semestre_id` ASC),
  CONSTRAINT `fk_estudiantes_personas`
    FOREIGN KEY (`persona_id`)
    REFERENCES `sistema_asistencias`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiantes_semestres`
    FOREIGN KEY (`semestre_id`)
    REFERENCES `sistema_asistencias`.`semestres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `semestre_id` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `codigo` VARCHAR(4) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cursos_semestres_idx` (`semestre_id` ASC),
  CONSTRAINT `fk_cursos_semestres`
    FOREIGN KEY (`semestre_id`)
    REFERENCES `sistema_asistencias`.`semestres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`asistencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`asistencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `curso_id` INT NOT NULL,
  `aula` VARCHAR(3) NULL,
  `tema` VARCHAR(50) NULL,
  `software` VARCHAR(20) NULL,
  `avance` INT NULL,
  `fecha` DATE NULL,
  `proyector` INT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_asistencias_cursos_idx` (`curso_id` ASC),
  CONSTRAINT `fk_asistencias_cursos`
    FOREIGN KEY (`curso_id`)
    REFERENCES `sistema_asistencias`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`estudiantes-cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`estudiantes-cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estudiante_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_asignados_estudiantes_idx` (`estudiante_id` ASC),
  INDEX `fk_estudiantes-cursos_cursos_idx` (`curso_id` ASC),
  CONSTRAINT `fk_estudiantes-cursos_estudiantes`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `sistema_asistencias`.`estudiantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiantes-cursos_cursos`
    FOREIGN KEY (`curso_id`)
    REFERENCES `sistema_asistencias`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`docentes-cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`docentes-cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_docentes-cursos_docentes_idx` (`user_id` ASC),
  INDEX `fk_docentes-cursos_cursos_idx` (`curso_id` ASC),
  CONSTRAINT `fk_docentes-cursos_docentes`
    FOREIGN KEY (`user_id`)
    REFERENCES `sistema_asistencias`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_docentes-cursos_cursos`
    FOREIGN KEY (`curso_id`)
    REFERENCES `sistema_asistencias`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_asistencias`.`asignados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_asistencias`.`asignados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estudiante_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_asignados_estudiantes_idx` (`estudiante_id` ASC),
  INDEX `fk_asignados_cursos_idx` (`curso_id` ASC),
  CONSTRAINT `fk_asignados_estudiantes`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `sistema_asistencias`.`estudiantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignados_cursos`
    FOREIGN KEY (`curso_id`)
    REFERENCES `sistema_asistencias`.`asistencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
